
motor:
  setup:
    # Port to which Motor controller is connected.
    port: COM3
    baudrate: 9600
    check_range: False
  x_axis:
    l_speed: 400
    f_speed: 400
    rate: 20
    s_rate: 20
  y_axis:
    l_speed: 400
    f_speed: 400
    rate: 20
    s_rate: 20
  initial_position: 
    x: 0
    y: 0

laser:
  setup:
    # Port to which Arduino is connected.
    port: COM7
    baudrate: 9600
    # Enter delay duration in seconds.
    delay_duration: 0.5