
image:
  setup:
    # Maximum image size is 100*100.
    x_size: 100
    y_size: 100
    intensity: 0.35

motor:
  setup:
    # Port to which Motor controller is connected.
    port: COM3
    baudrate: 9600
    # Check (-2000, -2000) to (2000, 2000). 
    # Boolean: True or False.
    check_range: False
  x_axis:
    l_speed: 400
    f_speed: 400
    rate: 20
    s_rate: 20
  y_axis:
    l_speed: 400
    f_speed: 400
    rate: 20
    s_rate: 20
  initial_position: 
    x: 0
    y: 0

laser:
  setup:
    # Port to which Arduino is connected.
    port: COM7
    baudrate: 9600
    # Enter delay duration in seconds.
    duration_time: 0.5